version: '3'

services:
  peerjs:
    build:
      context: .
      dockerfile: "./Docker/PeerJS/Dockerfile"
    ports:
      - "127.0.0.1:5000:5000"
    
  signalingserver:
    build:
      context: .
      dockerfile: "./Docker/Signaling Server/Dockerfile"
    ports:
      - "127.0.0.1:8000:8000"
